// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNMTD.Data;

#nullable disable

namespace PNMTD.Migrations
{
    [DbContext(typeof(PnmtdDbContext))]
    [Migration("20231014233705_DnsZones")]
    partial class DnsZones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("PNMTD.Models.Db.DnsZoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoneFileContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dnszones");
                });

            modelBuilder.Entity("PNMTD.Models.Db.DnsZoneEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DnsZoneId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ignore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TTL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DnsZoneId");

                    b.ToTable("dnszoneentries");
                });

            modelBuilder.Entity("PNMTD.Models.Db.DnsZoneLogEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DnsZoneEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DnsZoneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DnsZoneEntryId");

                    b.HasIndex("DnsZoneId");

                    b.ToTable("dnszonelogentries");
                });

            modelBuilder.Entity("PNMTD.Models.Db.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("PNMTD.Models.Db.HostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("hosts");
                });

            modelBuilder.Entity("PNMTD.Models.Db.KeyValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("keyvalues");
                });

            modelBuilder.Entity("PNMTD.Models.Db.MailInputRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyTest")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtractMessageRegex")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailTest")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromTest")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OkCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OkTest")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SensorOutputId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectTest")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SensorOutputId");

                    b.ToTable("mailinputrules");
                });

            modelBuilder.Entity("PNMTD.Models.Db.MailLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Processed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProcessedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedById");

                    b.ToTable("maillogs");
                });

            modelBuilder.Entity("PNMTD.Models.Db.NotificationRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("notificationrules");
                });

            modelBuilder.Entity("PNMTD.Models.Db.NotificationRuleEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoAction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NotificationRuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("NotificationRuleId");

                    b.ToTable("notificationruleevent");
                });

            modelBuilder.Entity("PNMTD.Models.Db.NotificationRuleSensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NotificationRuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameter")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotificationRuleId");

                    b.HasIndex("SensorId");

                    b.ToTable("NotificationRuleSensor");
                });

            modelBuilder.Entity("PNMTD.Models.Db.SensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GracePeriod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ignore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OlderSiblingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OlderSiblingId");

                    b.HasIndex("ParentId");

                    b.ToTable("sensors");
                });

            modelBuilder.Entity("PNMTD.Models.Db.DnsZoneEntryEntity", b =>
                {
                    b.HasOne("PNMTD.Models.Db.DnsZoneEntity", "DnsZone")
                        .WithMany("DnsZoneEntries")
                        .HasForeignKey("DnsZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DnsZone");
                });

            modelBuilder.Entity("PNMTD.Models.Db.DnsZoneLogEntryEntity", b =>
                {
                    b.HasOne("PNMTD.Models.Db.DnsZoneEntryEntity", "DnsZoneEntry")
                        .WithMany("DnsZoneLogEntries")
                        .HasForeignKey("DnsZoneEntryId");

                    b.HasOne("PNMTD.Models.Db.DnsZoneEntity", "DnsZone")
                        .WithMany()
                        .HasForeignKey("DnsZoneId");

                    b.Navigation("DnsZone");

                    b.Navigation("DnsZoneEntry");
                });

            modelBuilder.Entity("PNMTD.Models.Db.EventEntity", b =>
                {
                    b.HasOne("PNMTD.Models.Db.SensorEntity", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("PNMTD.Models.Db.MailInputRuleEntity", b =>
                {
                    b.HasOne("PNMTD.Models.Db.SensorEntity", "SensorOutput")
                        .WithMany()
                        .HasForeignKey("SensorOutputId");

                    b.Navigation("SensorOutput");
                });

            modelBuilder.Entity("PNMTD.Models.Db.MailLogEntity", b =>
                {
                    b.HasOne("PNMTD.Models.Db.MailInputRuleEntity", "ProcessedBy")
                        .WithMany()
                        .HasForeignKey("ProcessedById");

                    b.Navigation("ProcessedBy");
                });

            modelBuilder.Entity("PNMTD.Models.Db.NotificationRuleEventEntity", b =>
                {
                    b.HasOne("PNMTD.Models.Db.EventEntity", "Event")
                        .WithMany("NotificationRuleEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PNMTD.Models.Db.NotificationRuleEntity", "NotificationRule")
                        .WithMany()
                        .HasForeignKey("NotificationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("NotificationRule");
                });

            modelBuilder.Entity("PNMTD.Models.Db.NotificationRuleSensorEntity", b =>
                {
                    b.HasOne("PNMTD.Models.Db.NotificationRuleEntity", "NotificationRule")
                        .WithMany("SubscribedSensors")
                        .HasForeignKey("NotificationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PNMTD.Models.Db.SensorEntity", "Sensor")
                        .WithMany("SubscribedByNotifications")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationRule");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("PNMTD.Models.Db.SensorEntity", b =>
                {
                    b.HasOne("PNMTD.Models.Db.SensorEntity", "OlderSibling")
                        .WithMany()
                        .HasForeignKey("OlderSiblingId");

                    b.HasOne("PNMTD.Models.Db.HostEntity", "Parent")
                        .WithMany("Sensors")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OlderSibling");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PNMTD.Models.Db.DnsZoneEntity", b =>
                {
                    b.Navigation("DnsZoneEntries");
                });

            modelBuilder.Entity("PNMTD.Models.Db.DnsZoneEntryEntity", b =>
                {
                    b.Navigation("DnsZoneLogEntries");
                });

            modelBuilder.Entity("PNMTD.Models.Db.EventEntity", b =>
                {
                    b.Navigation("NotificationRuleEvents");
                });

            modelBuilder.Entity("PNMTD.Models.Db.HostEntity", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("PNMTD.Models.Db.NotificationRuleEntity", b =>
                {
                    b.Navigation("SubscribedSensors");
                });

            modelBuilder.Entity("PNMTD.Models.Db.SensorEntity", b =>
                {
                    b.Navigation("SubscribedByNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
